/**
 * Define static display texts of 
 */
const MenuItem:any  = {
  MENU_ITEM_DESKS: "MENU_ITEM_DESKS",
  MENU_ITEM_BOOKI: "MENU_ITEM_BOOKINGS",
  MENU_ITEM_RENTALS: "MENU_ITEM_RENTALS",
  MENU_ITEM_LOCATION_SETTING: "MENU_ITEM_LOCATION_SETTING",
  MENU_ITEM_AVAIABLE_HOURS: "MENU_ITEM_AVAIABLE_HOURS",
  MENU_ITEM_QR_CODES: "MENU_ITEM_QR_CODES",
  MENU_ITEM_PHOTOS: "MENU_ITEM_PHOTOS"
}

export default MenuItem;